[add_remove_abiword]
name = "Install/remove abiword"
command = "/bin/bash scripts/actions/add_remove_abiword"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Install or remove abiword"

[add_remove_libreoffice]
name = "Install/remove libreoffice"
command = "/bin/bash scripts/actions/add_remove_libreoffice"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Install or remove libreoffice"

[list_all_pads]
name = "List all existing pads"
command = "/bin/bash scripts/actions/list_all_pads"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "List all existing pads."

[reset_default_config]
name = "Reset the config file and restore a default one."
command = "/bin/bash scripts/actions/reset_default_config \"settings.json\""
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the config file settings.json."

[public_private]
name = "Move to public or private"
command = "/bin/bash scripts/actions/public_private"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Change the public access of the app."

    [public_private.arguments]
        [public_private.arguments.is_public]
            type = "boolean"
            ask = "Is it a public app ?"
            default = true
